--- 
- 
  become: true
  become_user: root
  hosts:  ci-server
  ignore_errors: true
  roles: 
    -
      role: geerlingguy.java
      become: yes
      java_packages:
        -
          openjdk-8-jdk
    -
      role: geerlingguy.jenkins
      become: yes

  tasks: 
    - 
      name: "Ping the hosts"
      ping: ~
    - 
      apt: "pkg=git state=latest"
      name: "Make sure Git is available"
  vars: 
    jenkins_version: "2.138"
    jenkins_hostname: localhost
    jenkins_http_port: 8080
    jenkins_jar_location: /opt/jenkins-cli.jar
    jenkins_plugins: "git sonar ssh nodejs"
    jenkins_repo_key_url: "http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key"
    jenkins_repo_url: "deb http://pkg.jenkins-ci.org/debian binary/"
